### ISSUE TITLE
Dept Checklist Overview is unusable in Firefox/IE

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#1618]
The overview page for the Department Head Checklist at
https://prime.uber.magfest.org/uber/dept_checklist/overview
is supposed to have a bunch of vertical column headers, which are styled using the following CSS definition:

```css
    th div {
        width: 1.2em;
        display: block;
        white-space: nowrap;
        filter: flipv fliph;
        writing-mode: tb-rl;
        -webkit-transform: rotate(-90deg);
        -moz-transform: rotate(-90deg);
        -ms-transform: rotate(-90deg);
        -o-transform: rotate(-90deg);
        transform: rotate(-90deg);
    }
```

This works in Chrome but not in IE or Firefox, and that's making it hard for some of our department heads who need to review items on the checklist to do their jobs.
